name: warframe_quick
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  easy_localization: ^3.0.2
  get_it: ^7.6.0
  dio: ^5.1.2
  get: ^4.6.5
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/translations/
      - assets/images/jpg/
      - assets/images/png/
      - assets/images/gif/